language: c

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: DjktS7O52Lkh3A303/3WIaYRoF+LkHseum/yG6Dacvzj22EPr+NO/apflLYxf5itb/JboZw2lA6a9Msnvfz1qYklLX2BAZrPqrZ+syf2Er1JrUDUI7Z2xxSWjPM5aB0WA9AVQ+orEPz1EoAbQj4uX4c1HFAlD7CScVxgEsV6TP8=

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install r-base-dev r-cran-httpuv r-cran-devtools
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check ${R_PKG}_*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - set -e
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"

after_failure:
  - cd ..; for i in `ls *.Rcheck/00*`; do cat $i; done
